name: docker_publish_production

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log into Docker Hub Container Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
    - name: Build the Docker image
      run: export VERSION=$(echo "${{ github.ref }}" | docker build . --file Dockerfile --tag mushare/urlooker:$(VERSION)
    
    - name: Push Docker image
      run: export VERSION=$(echo "${{ github.ref }}" | docker push mushare/urlooker:$(VERSION)
